version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn clean install -DskipTests -Perrorprone-compiler -e -pl :trino-hive-jdbc -am
      - run: mvn test
      - run: mvn package -e -pl :trino-hive-jdbc -am
